### ISSUE TITLE
Choose timezone dropdown not being initialized

### ISSUE THREAD

**Issue by hyperbyte** [rzeldent/TTGO-OpenWeather#11]
Hello

I've flashed the application on my TTGO T-Display but i'm not getting a timezone to select. 

Thanks for your work

Pedro

**Comment by rzeldent** [comment]
Hi Pedro,

Just retested this and I can confirm this is the case... Will take a look
at it!

Rene

**Comment by rzeldent** [comment]
Hi Pedro,

Thanks for mentioning this issue. Found the solution and merged a pull request.
Issue was caused by space optimization somewhere in the past.

Can you confirm the issue is resolved now?

**Comment by hyperbyte** [comment]
Hello, Rene

Reflashed and it's working fine now

Best Regards

Pedro
